### PR TITLE
Add ability to start at any beat within the song

### PR DESCRIPTION
**Pull request by eugene-bulkin**
In the interest of creating a tracker at some point, I added the ability to start play at any given beat, zero-indexed.

### CODE REVIEW

**Comment by meenie** [comment]
Hi,

Yes, I definitely want to do this.  I don't think your solution takes into account complex (6/8) or cut time (2/2) due to having to use `getDuration('quarter');`.  What needs to happen is looking at what the bottom number of the time signature is and use that to figure out what note is actually getting the beat.  So if it's a 4 then a it's a quarter note, it's an 8 then it's a dotted quarter net, and if it's a 2, it's a half note.  Technically 8 should use eighth notes but no one counts eighth notes in 6/8 time, they only count on the dotted quarter.

Let me know if you want to have a go and fix that, or if you want me to fix it up.

Thanks a ton for your help!

Cheers,
cody

**Comment by eugene-bulkin** [comment]
Ah, yes, I forgot about that! I'll take care of that later and resubmit the pull request.

**Comment by eugene-bulkin** [comment]
Time signatures are fixed now.

**Comment by meenie** [comment]
Hi Eugene,

Thanks for fixing up the commit :).  I'll be merging this in later today.

Cheers,
cody

**Comment by meenie** [comment]
Hi Eugene, could you please re-do your work on the new repo: https://github.com/meenie/band.js - I don't want to copy what you've done without giving you the commit credit.  I'll close this off for now.

**Pull request closed without merging**
